name: RHFest Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  validate:
    name: Validate plugin with RHFest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run RHFest
        uses: RotorHazard/rhfest-action@v1
